
###
POST http://127.0.0.1:3566/auth/resetPassword
Content-Type: application/json

{
  "email": "nanak@gmail.com",
  "password": "123456"

}

###
POST http://127.0.0.1:3566/auth/login
Content-Type: application/json

{
  "email": "nanak@gmail.com",
  "password": "123456"

}

###
POST http://127.0.0.1:3566/auth/register
Content-Type: application/json

{
  "fullName": "Nana Kwesi Otoo",
  "email": "nanak@gmail.com",
  "password": "123456",
  "avatar": "maker"
}

